style: dark
# listen_for_clients_preferred_style: true

header_pages:
  - index.md
  - about.md
  - contact.md
footer: '<a href="https://twitter.com/savyengineer">@savyengineer 📢</a>'
plugins:
  - jekyll-seo-tag